### ISSUE TITLE
Add a "remember me" checkbox on login page

### ISSUE THREAD

**Issue by marien-probesys** [Probesys/bileto#282]
See https://symfony.com/doc/current/security/remember_me.html

**Comment by Adibzadeh** [comment]
Hi, I would like to work on this feature, please assign it to me if it's okay and nobody else is already working on it.

**Comment by arya177** [comment]
Hello, I would like to work on this, but I'm not sure which permissions you're referring to.

**Comment by marien-probesys** [comment]
Hi, thanks for your proposal! I'm assigning the ticket to you.

I have to tell you that we plan this feature for the next release planed for the 8th May and it must be finished for the end of April. If it's not, I'll take over the ticket to finish it in time. Hopefully, you should have enough time! :blush: 

Let me know if you need any information!

**Comment by marien-probesys** [comment]
Hey there, did you have time to work on this feature? I postponed the date of the release to the 12th May, so you'll have a bit more time for it.

**Comment by Adibzadeh** [comment]
Hi, I was a little busy by work. Thank You. Yes I'll do it in the next few days.

**Comment by marien-probesys** [comment]
Hi, I'm taking over this ticket!

**Comment by Adibzadeh** [comment]
Okay. Sorry, I was extremely busy this past couple of weeks.

**Comment by marien-probesys** [comment]
No problem! :+1:
