### ISSUE TITLE
Allow to pass the language when creating a user with the command line

### ISSUE THREAD

**Issue by marien-probesys** [Probesys/bileto#490]
When creating a user with command line, its language is always English.
We should let the administrators to pass the language (`en_GB` or `fr_FR`) to the [CreateCommand](https://github.com/Probesys/bileto/blob/main/src/Command/Users/CreateCommand.php).
This option must be optional and default to `en_GB`.

**Comment by Gozyvee** [comment]
I just made an improvement to the code

**Comment by marien-probesys** [comment]
Duplicates https://github.com/Probesys/bileto/issues/530
