### ISSUE TITLE
Orphan parenthesis in the list of tickets

### ISSUE THREAD

**Issue by marien-probesys** [Probesys/bileto#498]
There is an orphan parenthesis in the list of tickets.
It appears only on incidents and in English.

![](https://github.com/Probesys/bileto/assets/107053378/5f62ee5b-6aeb-46fd-8c99-68c03ec83b98)

**Comment by sassani134** [comment]
Orphan parenthesis in the list of tickets #498

messages+intl-icu.en_GB.yaml 296

-tickets.list.incident_updated_on: 'Incident updated on <time datetime="{dateIso}">{date}</time>)'
+tickets.list.incident_updated_on: 'Incident updated on <time datetime="{dateIso}">{date}</time>'
