### ISSUE TITLE
A question about asset management!

### ISSUE THREAD

**Issue by Smiley-k** [Probesys/bileto#546]
Hi,

I have a question, is it possible to manage assets ? I mean the function of maintaining inventory (equipment, PCs, laptops, screens, servers). Maybe there is an automatic inventory agent like GLPI project. https://glpi-project.org/

**Comment by marien-probesys** [comment]
Hi, this is definitely on our roadmap, but I can't say when we'll start to work on it. We are focusing on our own needs, and getting the assistance part right. We are planning to use https://fusioninventory.org/, which is an agent for GLPI (and for the future [FusionSuite](https://fusionsuite.org/)).
